image:
  - Visual Studio 2017
  - Ubuntu
stack: jdk 8, node 8
skip_tags: true
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  JENKINS_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  JENKINS_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  JENKINS_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==

init:
  - cmd: "choco install gradle -s %JENKINS_ARTIFACTORY_URL%/api/nuget/choco -u %JENKINS_ARTIFACTORY_USERNAME% -p %JENKINS_ARTIFACTORY_PASSWORD% && refreshenv"
  - sh: sudo apt -yq update && sudo apt upgrade -y maven gradle
  - sh: export MAVEN_HOME=/usr/share/maven && export GRADLE_HOME=/opt/gradle

test_script:
  - mvn -V clean verify

cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
  - /home/appveyor/.m2/ -> pom.xml

build: off