updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsReleaseGit --context "$step_name"

resources:
  - name: jenkinsReleaseGit
    type: GitRepo
    configuration:
      path: yahavi/jenkins-artifactory-plugin
      gitProvider: yahav_github
      buildOn:
        commit: false
        tagCreate: true

pipelines:
  - name: release_jenkins_plugin
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: "artifactory-jenkins-plugin"
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: build_release
        type: Bash
        configuration:
          inputResources:
            - name: jenkinsReleaseGit
          integrations:
            - name: jfrog
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jenkinsReleaseGit_resourcePath
            # Restore .m2 cache
            - restore_cache_files m2_home ${HOME}/.m2

            # Install Java 8
            - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
            - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
            - source "/root/.sdkman/bin/sdkman-init.sh" && sdk update && sdk install java `sdk list java | grep -E "8.*hs-adpt" | head -1 | awk '{print $NF}'` && java -version

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Run mvn
            - ./jfrog rt c jfrog --url $int_jfrog_rt_url --user $int_jfrog_rt_user --password $int_jfrog_rt_password
            - ./jfrog rt mvnc
              --server-id-resolve jfrog --repo-resolve-releases jfrog-dependencies --repo-resolve-snapshots jfrog-dependencies
              --server-id-deploy jfrog --repo-deploy-releases releases --repo-deploy-snapshots snapshots
            - ./jfrog rt mvn clean install
            - ./jfrog rt bp
          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsReleaseGit_resourcePath/target/surefire-reports/

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home

            - *UPDATE_COMMIT_STATUS