updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsReleaseGit --context "$step_name"

resources:
  - name: jenkinsReleaseGit
    type: GitRepo
    configuration:
      path: yahavi/jenkins-artifactory-plugin
      gitProvider: yahav_github
      buildOn:
        commit: false

pipelines:
  - name: release_jenkins_plugin
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: maven
            tag: 3.6.3-adoptopenjdk-8
      environmentVariables:
        readOnly:
          CI: "true"
          M2_HOME: $MAVEN_HOME
          JFROG_CLI_BUILD_NAME: "artifactory-jenkins-plugin"
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: build_release
        type: Bash
        configuration:
          environmentVariables:
            NEXT_VERSION: 0.0.0
            NEXT_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT
          inputResources:
            - name: jenkinsReleaseGit
          integrations:
            - name: jfrog
        execution:
          onStart:
            - apt update && apt install -y gettext-base jq
            - *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jenkinsReleaseGit_resourcePath

            # Make sure versions provided
            - [ -n '$NEXT_VERSION' -a '$NEXT_VERSION' != "0.0.0" ]
            - [ -n '$NEXT_DEVELOPMENT_VERSION' -a '$NEXT_DEVELOPMENT_VERSION' != "0.0.0" ]

            # Make sure tag does not exist
            - ! git rev-parse artifactory-1.0.0 >/dev/null 2>&1

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog rt c jfrog --url $int_jfrog_rt_url --user $int_jfrog_rt_user --password $int_jfrog_rt_password
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases jfrog-dependencies --repo-resolve-snapshots jfrog-dependencies
              --server-id-deploy jfrog --repo-deploy-releases releases --repo-deploy-snapshots snapshots

            # Update version
            - ./jfrog rt mvn versions:set -DnewVersion=${NEXT_VERSION} -B
            - git commit -am "[artifactory-release] Release version ${NEXT_VERSION}"
            - git tag artifactory-${NEXT_VERSION}
            - git push --tags

            # Run mvn install
            - ./jfrog rt mvn clean install -B
            - ./jfrog rt bp

            # Update next development version
            - ./jfrog rt mvn versions:set -DnewVersion=${NEXT_DEVELOPMENT_VERSION}
            - git commit -am "[artifactory-release] Next development version"
          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsReleaseGit_resourcePath/target/surefire-reports/

            - *UPDATE_COMMIT_STATUS