updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsSnapshotGit --context "$step_name"

resources:
  - name: jenkinsSnapshotGit
    type: GitRepo
    configuration:
      path: yahavi/jenkins-artifactory-plugin
      gitProvider: yahav_github
      buildOn:
        tagCreate: true

pipelines:
  - name: create_jenkins_snapshot
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: maven
            tag: 3.6.3-adoptopenjdk-8
      environmentVariables:
        readOnly:
          CI: "true"
          M2_HOME: $MAVEN_HOME
          JFROG_CLI_BUILD_NAME: "jenkins-plugin-dev"
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: build_snapshot
        type: Bash
        configuration:
          inputResources:
            - name: jenkinsSnapshotGit
          integrations:
            - name: jfrog
            - name: ojo
        execution:
          onStart:
            - apt update && apt install -y gettext-base jq
            - *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jenkinsSnapshotGit_resourcePath
            # Restore .m2 cache
            - restore_cache_files m2_home ${HOME}/.m2

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Run mvn
            - ./jfrog rt c jfrog --url $int_jfrog_rt_url --user $int_jfrog_rt_user --password $int_jfrog_rt_password
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases libs-release --repo-resolve-snapshots libs-snapshot
              --server-id-deploy jfrog --repo-deploy-releases libs-release-local --repo-deploy-snapshots libs-snapshot-local
            - ./jfrog rt mvn clean install -UB javadoc:jar source:jar
            - ./jfrog rt bag
            - ./jfrog rt bp
          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsSnapshotGit_resourcePath/target/surefire-reports/

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home

            - *UPDATE_COMMIT_STATUS