updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsReleaseGit --context "$step_name"

resources:
  - name: jenkinsReleaseGit
    type: GitRepo
    configuration:
      path: yahavi/jenkins-artifactory-plugin
      gitProvider: yahav_github
      buildOn:
        commit: false

pipelines:
  - name: release_jenkins_plugin
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: maven
            tag: 3.6.3-adoptopenjdk-8
      environmentVariables:
        readOnly:
          CI: "true"
          M2_HOME: $MAVEN_HOME
          JFROG_CLI_BUILD_NAME: "artifactory-jenkins-plugin"
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: build_release
        type: Bash
        configuration:
          environmentVariables:
            JENKINS_ARTIFACTORY_PLUGIN_VERSION: 0.0.0
          inputResources:
            - name: jenkinsReleaseGit
          integrations:
            - name: jfrog
        execution:
          onStart:
            - apt update && apt install -y gettext-base jq
            - *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jenkinsReleaseGit_resourcePath

            # Make sure tag is provided
            - if [[ -z "${JENKINS_ARTIFACTORY_PLUGIN_TAG}" ] | ["$JENKINS_ARTIFACTORY_PLUGIN_TAG" = "0.0.0"]; then
              echo "JENKINS_ARTIFACTORY_PLUGIN_TAG env var is mandatory; exit 1

            # Make sure tag is not exist
            - if ! rev-parse artifactory-$JENKINS_ARTIFACTORY_PLUGIN_TAG >/dev/null 2>&1; then
              echo "Tag $JENKINS_ARTIFACTORY_PLUGIN_TAG is already exist"

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Run mvn
            - ./jfrog rt c jfrog --url $int_jfrog_rt_url --user $int_jfrog_rt_user --password $int_jfrog_rt_password
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases jfrog-dependencies --repo-resolve-snapshots jfrog-dependencies
              --server-id-deploy jfrog --repo-deploy-releases releases --repo-deploy-snapshots snapshots
            - ./jfrog rt mvn versions:set clean install -B
            - ./jfrog rt bag
            - ./jfrog rt bp
          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsReleaseGit_resourcePath/target/surefire-reports/

            - *UPDATE_COMMIT_STATUS